WARNING:app.db.UserModel:2020-06-10 01:59:14,321:role:This is the users role_id: 100
WARNING:app.db.UserModel:2020-06-10 01:59:14,424:role:This is the users role_id: 4
WARNING:app.db.UserModel:2020-06-10 01:59:14,436:role:This is the users role_id: 4
ERROR:app.db.UserModel:2020-06-12 04:25:26,482:is_following:Something went wrong when trying to determine whether the user follows Elvis.
Traceback (most recent call last):
  File "/home/elvis/Desktop/software_projects/python/flaskPG_practice/app/db/UserModel.py", line 127, in is_following
    follower_id = cursor.fetchone(sql_query,(user.id,self.id))
TypeError: fetchone() takes no arguments (2 given)
ERROR:app.db.UserModel:2020-06-12 04:31:02,161:is_following:Something went wrong when trying to determine whether the user follows Jayden.
Traceback (most recent call last):
  File "/home/elvis/Desktop/software_projects/python/flaskPG_practice/app/db/UserModel.py", line 129, in is_following
    if len(follower_id) == 0 or follower_id[0] != self.id:
TypeError: object of type 'NoneType' has no len()
